from typing import List, Tuple

import numpy as np

class PolylabelError(ValueError): ...
class PolylabelShapeError(TypeError): ...

def polylabel_ext(
    exterior: List[Tuple[float, float]], tolerance: float
) -> Tuple[float, float]: ...
def polylabel_ext_np(exterior: np.ndarray, tolerance: float) -> Tuple[float, float]: ...
