name: Benchmark

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: messense/maturin-action@v1
        with:
          command: build --release
      - run: pip install . -r requirements.txt
      - run: pytest benchmarks
